"use client";
import { useEffect,useMemo,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import { computeClipetStandings, finalClipetRanking, makeFinalSeeds, makePhase2Seeds, phase1Matches, type ClipetMatch, type ClipetTeam } from "@/lib/clipet";

type Tournament={id:string;title:string;category:string|null;format:string|null;phase1_locked:boolean;match_duration_min:number;rotation_duration_min:number;num_fields:number;end_time:string};
function minOf(t:string){const [h,m]=String(t).slice(0,5).split(':').map(Number);return h*60+m} function timeOf(n:number){return `${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
export default function ClipetPilot(){const router=useRouter();const {id}=useParams();const tournamentId=String(id);const [t,setT]=useState<Tournament|null>(null);const [teams,setTeams]=useState<ClipetTeam[]>([]);const [matches,setMatches]=useState<ClipetMatch[]>([]);const [status,setStatus]=useState('Chargement…');
 async function load(){const {data:a}=await supabase.auth.getUser();if(!a.user)return router.push('/login');const [{data:tt,error:te},{data:tm,error:tme},{data:mm,error:me}]=await Promise.all([supabase.from('tournaments').select('id,title,category,format,phase1_locked,match_duration_min,rotation_duration_min,num_fields,end_time').eq('id',tournamentId).single(),supabase.from('teams').select('id,name,club_name,squad_number,challenge_disqualified').eq('tournament_id',tournamentId).order('created_at'),supabase.from('matches').select('id,match_number,phase,stage,home_team_id,away_team_id,home_score,away_score,status,penalty_home,penalty_away,winner_team_id,start_time,field_idx').eq('tournament_id',tournamentId).order('match_number')]);if(te||tme||me)return setStatus((te||tme||me)?.message||'Erreur');setT(tt as Tournament);setTeams((tm??[]) as ClipetTeam[]);setMatches((mm??[]) as any);setStatus('');}
 useEffect(()=>{load()},[tournamentId]); const p1=useMemo(()=>phase1Matches(matches),[matches]);const standing=useMemo(()=>computeClipetStandings(teams,p1),[teams,p1]);const finalRanking=useMemo(()=>finalClipetRanking(teams,matches),[teams,matches]);
 const p1Played=p1.filter(m=>m.status==='played').length; const has4653=matches.some(m=>Number(m.match_number)===53); const has55=matches.some(m=>Number(m.match_number)===55);
 function slotsFor(count:number){if(!t)return[];const slot=(t.match_duration_min+t.rotation_duration_min);const latest=matches.reduce((mx,m:any)=>Math.max(mx,minOf(m.start_time||'00:00')),0);let cur=latest+slot;const out:{start_time:string;field_idx:number}[]=[];for(let i=0;i<count;i++){const field=(i%Math.max(1,t.num_fields))+1;if(i>0&&field===1)cur+=slot;out.push({start_time:timeOf(cur),field_idx:field})}return out}
 async function generatePhase2(){if(!t)return;if(teams.length!==10)return setStatus('Il faut exactement 10 équipes.');if(p1.length!==45||p1Played!==45)return setStatus(`Phase 1 incomplète : ${p1Played}/45 matchs validés.`);if(has4653)return setStatus('M46 à M53 existent déjà.');const seeds=makePhase2Seeds(standing);const slots=slotsFor(seeds.length);const payload=seeds.map((s,i)=>({...s,tournament_id:tournamentId,phase:'phase2',start_time:slots[i].start_time,field_idx:slots[i].field_idx,status:'scheduled'}));const {error}=await supabase.from('matches').insert(payload);if(error)return setStatus(error.message);await supabase.from('tournaments').update({phase1_locked:true}).eq('id',tournamentId);setStatus('M46 à M53 générés ✅');await load()}
 async function generateFinals(){const m46=matches.find(m=>Number(m.match_number)===46),m47=matches.find(m=>Number(m.match_number)===47);if(!m46||!m47)return setStatus('M46/M47 absents.');if(has55)return setStatus('M54/M55 existent déjà.');try{const seeds=makeFinalSeeds(m46,m47);const slots=slotsFor(2);const {error}=await supabase.from('matches').insert(seeds.map((s,i)=>({...s,tournament_id:tournamentId,phase:'phase2',start_time:slots[i].start_time,field_idx:slots[i].field_idx,status:'scheduled'})));if(error)return setStatus(error.message);setStatus('M54 et M55 générés ✅');await load()}catch(e:any){setStatus(e.message)}}
 return <main className="min-h-screen bg-slate-100 p-6"><div className="max-w-6xl mx-auto space-y-4"><div className="bg-white rounded-2xl shadow p-6 flex justify-between flex-wrap gap-3"><div><h1 className="text-2xl font-extrabold">🏆 Pilotage Michel Clipet {t?.category?`— ${t.category}`:''}</h1><p className="text-sm text-gray-500">Phase 1 M1–M45 → classement → M46–M53 → M54/M55.</p></div><button className="bg-gray-200 px-4 py-2 rounded-xl" onClick={()=>router.push(`/dashboard/tournaments/${tournamentId}`)}>← Tournoi</button></div>{status&&<div className="bg-white rounded-xl shadow p-4">{status}</div>}
 <div className="grid md:grid-cols-3 gap-4"><div className="bg-white rounded-2xl shadow p-5"><div className="text-sm text-gray-500">Phase 1</div><div className="text-3xl font-extrabold">{p1Played}/45</div><div className="text-xs text-gray-500">matchs validés</div></div><div className="bg-white rounded-2xl shadow p-5"><div className="text-sm text-gray-500">Phase 2</div><div className="text-3xl font-extrabold">{matches.filter(m=>Number(m.match_number)>=46).length}/10</div><div className="text-xs text-gray-500">matchs créés</div></div><div className="bg-white rounded-2xl shadow p-5"><div className="text-sm text-gray-500">Équipes</div><div className="text-3xl font-extrabold">{teams.length}/10</div></div></div>
 <div className="bg-white rounded-2xl shadow p-6"><div className="flex gap-2 flex-wrap mb-4"><button onClick={generatePhase2} disabled={has4653||p1Played!==45} className="bg-blue-600 disabled:bg-gray-300 text-white px-4 py-3 rounded-xl font-bold">Figer phase 1 + générer M46–M53</button><button onClick={generateFinals} disabled={!has4653||has55} className="bg-red-600 disabled:bg-gray-300 text-white px-4 py-3 rounded-xl font-bold">Générer M54–M55</button><button onClick={()=>router.push(`/dashboard/tournaments/${tournamentId}/matches`)} className="bg-gray-200 px-4 py-3 rounded-xl">Saisir les résultats</button></div><h2 className="font-extrabold mb-2">Classement phase 1</h2><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">#</th><th>Équipe</th><th>Pts</th><th>BP</th><th>BC</th><th>J</th></tr></thead><tbody>{standing.map((r,i)=><tr key={r.team_id} className="border-b"><td className="p-2 font-bold">{i+1}</td><td>{r.team_name}</td><td className="font-extrabold">{r.pts}</td><td>{r.gf}</td><td>{r.ga}</td><td>{r.played}</td></tr>)}</tbody></table></div><p className="text-xs text-gray-500 mt-2">Départage : points → buts marqués → buts encaissés. En égalité parfaite, appliquer le tirage au sort réglementaire et ajuster manuellement l’ordre avant génération si nécessaire.</p></div>
 {finalRanking&&<div className="bg-white rounded-2xl shadow p-6"><h2 className="font-extrabold text-xl mb-3">Classement final</h2>{finalRanking.map(r=><div key={r.team.id} className="flex justify-between border-b p-2"><span><b>{r.rank}.</b> {r.team.name}</span><b>{r.challenge_points} pts Challenge</b></div>)}</div>}
 </div></main>}
