"use client";
import { useEffect, useMemo, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import { createClient } from "@supabase/supabase-js";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type Player={jersey_number:string;last_name:string;first_name:string;license_number:string;no_license:boolean;birth_date:string};
type Staff={role:string;last_name:string;first_name:string;license_number:string;no_license:boolean;birth_date:string;phone:string};
type Tournament={id:string;title:string|null;tournament_date:string|null;venue:string|null;min_players_per_team:number|null;max_players_per_team:number|null;min_staff_per_team:number|null;max_staff_per_team:number|null};
type Team={id:string;name:string|null;club_name:string|null;email:string|null;colors:string[]|null;logo_url:string|null;staff:Staff[]|null;sheet_validated_at:string|null;sheet_validation_incomplete:boolean|null};
type Challenge={id:string;title:string|null;event_date:string|null;venue:string|null;display_logo_url:string|null;min_players_per_team:number|null;max_players_per_team:number|null;min_staff_per_team:number|null;max_staff_per_team:number|null};
const emptyPlayer=():Player=>({jersey_number:"",last_name:"",first_name:"",license_number:"",no_license:false,birth_date:""});
const emptyStaff=():Staff=>({role:"",last_name:"",first_name:"",license_number:"",no_license:false,birth_date:"",phone:""});
const trim=(v:string)=>String(v??"").trim();
const begunPlayer=(p:Player)=>Boolean(trim(p.jersey_number)||trim(p.last_name)||trim(p.first_name)||trim(p.license_number)||trim(p.birth_date));
const completePlayer=(p:Player)=>Boolean(trim(p.jersey_number)&&trim(p.last_name)&&trim(p.first_name)&&(p.no_license||trim(p.license_number))&&trim(p.birth_date));
const begunStaff=(p:Staff)=>Boolean(trim(p.role)||trim(p.last_name)||trim(p.first_name)||trim(p.license_number)||trim(p.birth_date)||trim(p.phone));
const completeStaff=(p:Staff)=>Boolean(trim(p.role)&&trim(p.last_name)&&trim(p.first_name)&&(p.no_license||trim(p.license_number))&&trim(p.birth_date)&&trim(p.phone));
const dateFR=(v:string|null|undefined)=>v?new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString("fr-FR",{day:"2-digit",month:"long",year:"numeric"}):"Date à confirmer";
const hex=(v:string|undefined,f:string)=>/^#[0-9a-f]{6}$/i.test(v??"")?v!:f;
function contrast(bg:string){const n=parseInt(bg.slice(1),16),l=((n>>16)*299+((n>>8)&255)*587+(n&255)*114)/1000;return l>145?"#0f172a":"#fff"}

export default function PublicTeamSheet(){
 const params=useParams(),search=useSearchParams();const tournamentId=String(params.id),teamId=String(params.teamId),token=search.get("token")??"";
 const client=useMemo(()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{global:{headers:{"x-team-sheet-token":token}},auth:{persistSession:false}}),[token]);
 const [tournament,setTournament]=useState<Tournament|null>(null),[team,setTeam]=useState<Team|null>(null),[challenge,setChallenge]=useState<Challenge|null>(null);
 const [players,setPlayers]=useState<Player[]>([]),[staff,setStaff]=useState<Staff[]>([]),[status,setStatus]=useState("Chargement de la fiche…");const [saving,setSaving]=useState(false),[pdfBusy,setPdfBusy]=useState(false);
 const limits=useMemo(()=>({minPlayers:Number(challenge?.min_players_per_team??tournament?.min_players_per_team??1),maxPlayers:Number(challenge?.max_players_per_team??tournament?.max_players_per_team??7),minStaff:Number(challenge?.min_staff_per_team??tournament?.min_staff_per_team??1),maxStaff:Number(challenge?.max_staff_per_team??tournament?.max_staff_per_team??5)}),[challenge,tournament]);
 const c1=hex(team?.colors?.[0],"#0b2f47"),c2=hex(team?.colors?.[1],"#2563eb"),c3=hex(team?.colors?.[2],"#f8fafc");const title=challenge?.title||tournament?.title||"Tournoi",eventDate=challenge?.event_date||tournament?.tournament_date,venue=challenge?.venue||tournament?.venue||"Lieu à confirmer";
 useEffect(()=>{if(!token){setStatus("Lien invalide : jeton d’accès manquant.");return;}let alive=true;(async()=>{
  const [{data:t,error:te},{data:tm,error:tme},{data:pl,error:pe},{data:link}]=await Promise.all([
   client.from("tournaments").select("id,title,tournament_date,venue,min_players_per_team,max_players_per_team,min_staff_per_team,max_staff_per_team").eq("id",tournamentId).single(),
   client.from("teams").select("id,name,club_name,email,colors,logo_url,staff,sheet_validated_at,sheet_validation_incomplete").eq("id",teamId).eq("tournament_id",tournamentId).single(),
   client.from("players").select("jersey_number,last_name,first_name,license_number,birth_date").eq("team_id",teamId).order("jersey_number"),
   client.from("challenge_tournaments").select("challenge_id").eq("tournament_id",tournamentId).limit(1).maybeSingle()]);
  if(!alive)return;if(te||tme||pe){setStatus("Ce lien est invalide ou n’autorise pas l’accès à cette fiche.");return;}let ch:Challenge|null=null;
  if(link?.challenge_id){const {data}=await client.from("challenges").select("id,title,event_date,venue,display_logo_url,min_players_per_team,max_players_per_team,min_staff_per_team,max_staff_per_team").eq("id",link.challenge_id).maybeSingle();ch=data as Challenge|null;}
  if(!alive)return;setTournament(t as Tournament);setTeam(tm as Team);setChallenge(ch);const maxP=Number(ch?.max_players_per_team??t?.max_players_per_team??7),maxS=Number(ch?.max_staff_per_team??t?.max_staff_per_team??5);
  const lp=(pl??[]).map((p:any)=>({...emptyPlayer(),...p,jersey_number:p.jersey_number==null?"":String(p.jersey_number),birth_date:p.birth_date??"",no_license:!p.license_number}));const ls=Array.isArray(tm?.staff)?(tm.staff as Staff[]).map(s=>({...emptyStaff(),...s})):[];
  setPlayers(Array.from({length:Math.max(maxP,lp.length)},(_,i)=>lp[i]??emptyPlayer()));setStaff(Array.from({length:Math.max(maxS,ls.length)},(_,i)=>ls[i]??emptyStaff()));setStatus("");
 })();return()=>{alive=false}},[client,teamId,token,tournamentId]);
 const setP=(i:number,k:keyof Player,v:string|boolean)=>setPlayers(x=>x.map((p,j)=>j===i?{...p,[k]:v}:p));const setS=(i:number,k:keyof Staff,v:string|boolean)=>setStaff(x=>x.map((p,j)=>j===i?{...p,[k]:v}:p));
 async function validate(){const activeP=players.filter(begunPlayer),activeS=staff.filter(begunStaff);const incomplete=activeP.length<limits.minPlayers||activeS.length<limits.minStaff||activeP.some(p=>!completePlayer(p))||activeS.some(s=>!completeStaff(s));
  const message=incomplete?"Tous les champs n’ont pas été renseignés. Souhaitez-vous valider votre effectif quand même ?":"Vous confirmez l’exactitude des données enregistrées dans cette fiche d’équipe ? En cas de révision, signalez-la à l’organisation.";if(!window.confirm(message))return;
  setSaving(true);setStatus("");const pp=activeP.map(p=>({first_name:trim(p.first_name),last_name:trim(p.last_name),jersey_number:Number(p.jersey_number),license_number:trim(p.license_number),no_license:p.no_license,birth_date:p.birth_date||null}));const ps=activeS.map(s=>({...s,role:trim(s.role),first_name:trim(s.first_name),last_name:trim(s.last_name),license_number:trim(s.license_number),phone:trim(s.phone)}));
  const {error}=await client.rpc("save_public_team_sheet",{p_team_id:teamId,p_tournament_id:tournamentId,p_token:token,p_players:pp,p_staff:ps,p_incomplete:incomplete});setSaving(false);if(error){setStatus("L’enregistrement a échoué : "+error.message);return;}setTeam(v=>v?{...v,staff:ps,sheet_validated_at:new Date().toISOString(),sheet_validation_incomplete:incomplete}:v);setStatus("Fiche enregistrée avec succès. Vous pouvez la rouvrir et la modifier à tout moment.");}
 async function exportPdf(){if(!team||!tournament)return;setPdfBusy(true);const doc=new jsPDF();doc.setFillColor(c1);doc.rect(0,0,210,45,"F");doc.setTextColor(contrast(c1));doc.setFontSize(9);doc.text("DOPPIETTA GESTION TOURNAMENT",14,12);doc.setFontSize(20);doc.setFont("helvetica","bold");doc.text("FICHE D’ÉQUIPE",14,25);doc.setFontSize(11);doc.text(title,14,34);doc.setTextColor(15,23,42);doc.setFont("helvetica","normal");doc.setFontSize(10);doc.text(`${dateFR(eventDate)} · ${venue}`,14,55);doc.text(`Club : ${team.club_name||team.name||"—"}`,14,62);doc.text(`Équipe : ${team.name||"—"}`,14,69);
  autoTable(doc,{startY:78,head:[["N°","Nom","Prénom","Licence","Naissance"]],body:players.filter(begunPlayer).map(p=>[p.jersey_number,p.last_name,p.first_name,p.no_license?"Sans licence":p.license_number,dateFR(p.birth_date)]),headStyles:{fillColor:c1},styles:{fontSize:9}});const y=(doc as any).lastAutoTable.finalY+10;autoTable(doc,{startY:y,head:[["Fonction","Nom","Prénom","Licence","Naissance","Téléphone"]],body:staff.filter(begunStaff).map(s=>[s.role,s.last_name,s.first_name,s.no_license?"Sans licence":s.license_number,dateFR(s.birth_date),s.phone]),headStyles:{fillColor:c2},styles:{fontSize:8}});doc.save(`fiche-equipe-${(team.name||"equipe").replace(/[^a-z0-9]+/gi,"-").toLowerCase()}.pdf`);setPdfBusy(false);}
 if(!team||!tournament)return <main className="min-h-screen grid place-items-center bg-slate-100 p-6"><div className="max-w-xl rounded-3xl bg-white p-8 shadow-xl text-slate-700">{status}</div></main>;
 return <main className="min-h-screen bg-slate-100"><header className="relative overflow-hidden" style={{background:`linear-gradient(120deg,${c1},${c2})`,color:contrast(c1)}}><div className="absolute inset-0 opacity-20" style={{backgroundImage:`radial-gradient(circle at 80% 15%,${c3} 0,transparent 34%)`}}/><div className="relative max-w-6xl mx-auto p-5 md:p-8 flex items-center gap-5">
  <div className="w-16 h-16 md:w-24 md:h-24 rounded-2xl bg-white/95 p-2 shadow-lg shrink-0 flex items-center justify-center">{challenge?.display_logo_url?<img src={challenge.display_logo_url} alt="Logo du challenge" className="max-w-full max-h-full object-contain"/>:<span className="text-3xl">🏆</span>}</div>
  <div className="min-w-0 flex-1"><p className="text-[10px] md:text-xs font-black tracking-[.18em] uppercase opacity-80">Doppietta Gestion Tournament</p><h1 className="text-xl md:text-4xl font-black leading-tight break-words">{title}</h1><p className="text-xs md:text-sm mt-1 opacity-90">{dateFR(eventDate)} · {venue}</p><div className="mt-3"><p className="text-xs uppercase tracking-widest opacity-75">{team.club_name||team.name}</p><p className="text-lg md:text-2xl font-bold break-words">{team.name}</p></div></div>
  <div className="w-20 h-20 md:w-28 md:h-28 rounded-2xl bg-white p-2 shadow-lg shrink-0 flex items-center justify-center">{team.logo_url?<img src={team.logo_url} alt={`Logo ${team.club_name||team.name}`} className="max-w-full max-h-full object-contain"/>:<span className="text-slate-500 text-center text-xs font-bold">LOGO<br/>CLUB</span>}</div>
 </div></header><div className="max-w-6xl mx-auto p-4 md:p-8 space-y-6">{status&&<div role="status" className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900 font-medium">{status}</div>}
 {team.sheet_validated_at&&<div className="rounded-2xl bg-white border p-4 flex items-center justify-between gap-3 flex-wrap"><span className="font-semibold text-slate-700">✓ Dernière validation : {new Date(team.sheet_validated_at).toLocaleString("fr-FR")}</span><span className={`text-xs font-bold px-3 py-1 rounded-full ${team.sheet_validation_incomplete?"bg-amber-100 text-amber-800":"bg-emerald-100 text-emerald-800"}`}>{team.sheet_validation_incomplete?"Validée avec informations manquantes":"Fiche complète"}</span></div>}
 <Sheet title="Effectif pratiquant" help={`De ${limits.minPlayers} à ${limits.maxPlayers} joueurs · complétez uniquement les lignes nécessaires.`}>{players.map((p,i)=><PlayerCard key={i} index={i} value={p} update={setP} accent={c1}/>)}</Sheet>
 <Sheet title="Effectif encadrant" help={`De ${limits.minStaff} à ${limits.maxStaff} encadrants.`}>{staff.map((s,i)=><StaffCard key={i} index={i} value={s} update={setS} accent={c2}/>)}</Sheet>
 <div className="sticky bottom-3 z-10 bg-white/95 backdrop-blur border shadow-2xl rounded-2xl p-3 flex gap-3 justify-end"><button onClick={exportPdf} disabled={pdfBusy} className="px-4 py-3 rounded-xl border font-bold text-slate-700 disabled:opacity-50">{pdfBusy?"Création…":"Extraire la fiche PDF"}</button><button onClick={validate} disabled={saving} className="px-6 py-3 rounded-xl font-black shadow text-white disabled:opacity-50" style={{background:c1}}>{saving?"Enregistrement…":"Valider la fiche"}</button></div></div></main>;
}
function Sheet({title,help,children}:{title:string;help:string;children:React.ReactNode}){return <section className="bg-white rounded-3xl shadow-sm border border-slate-200 overflow-hidden"><div className="p-5 md:p-7 border-b"><h2 className="text-xl md:text-2xl font-black text-slate-900">{title}</h2><p className="text-sm text-slate-500 mt-1">{help}</p></div><div className="p-3 md:p-6 space-y-3">{children}</div></section>}
const field="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none transition focus:ring-2 focus:ring-sky-300";
function PlayerCard({index,value,update,accent}:{index:number;value:Player;update:(i:number,k:keyof Player,v:string|boolean)=>void;accent:string}){return <div className="rounded-2xl border border-slate-200 p-3 md:p-4"><div className="grid grid-cols-2 md:grid-cols-[70px_1fr_1fr_1fr_170px] gap-3 items-start"><Label text="N°"><input inputMode="numeric" className={field} value={value.jersey_number} onChange={e=>update(index,"jersey_number",e.target.value.replace(/\D/g,""))}/></Label><Label text="Nom"><input className={field} value={value.last_name} onChange={e=>update(index,"last_name",e.target.value)}/></Label><Label text="Prénom"><input className={field} value={value.first_name} onChange={e=>update(index,"first_name",e.target.value)}/></Label><License value={value} index={index} update={update}/><Label text="Date de naissance"><input type="date" className={field} value={value.birth_date} onChange={e=>update(index,"birth_date",e.target.value)}/></Label></div><div className="h-1 rounded-full mt-3" style={{background:accent,opacity:.18}}/></div>}
function StaffCard({index,value,update,accent}:{index:number;value:Staff;update:(i:number,k:keyof Staff,v:string|boolean)=>void;accent:string}){return <div className="rounded-2xl border border-slate-200 p-3 md:p-4"><div className="grid grid-cols-2 md:grid-cols-3 gap-3"><Label text="Fonction"><input className={field} placeholder="Éducateur, dirigeant…" value={value.role} onChange={e=>update(index,"role",e.target.value)}/></Label><Label text="Nom"><input className={field} value={value.last_name} onChange={e=>update(index,"last_name",e.target.value)}/></Label><Label text="Prénom"><input className={field} value={value.first_name} onChange={e=>update(index,"first_name",e.target.value)}/></Label><License value={value} index={index} update={update}/><Label text="Date de naissance"><input type="date" className={field} value={value.birth_date} onChange={e=>update(index,"birth_date",e.target.value)}/></Label><Label text="Téléphone"><input type="tel" className={field} value={value.phone} onChange={e=>update(index,"phone",e.target.value)}/></Label></div><div className="h-1 rounded-full mt-3" style={{background:accent,opacity:.18}}/></div>}
function Label({text,children}:{text:string;children:React.ReactNode}){return <label className="text-xs font-bold text-slate-500">{text}{children}</label>}
function License<T extends Player|Staff>({value,index,update}:{value:T;index:number;update:(i:number,k:any,v:string|boolean)=>void}){return <div><Label text="N° de licence"><input className={field} disabled={value.no_license} value={value.license_number} onChange={e=>update(index,"license_number",e.target.value)}/></Label><label className="mt-1 flex gap-2 items-center text-xs text-slate-600"><input type="checkbox" checked={value.no_license} onChange={e=>update(index,"no_license",e.target.checked)}/> Sans licence</label></div>}
