"use client";
import { useEffect,useMemo,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import { computeClipetStandings, finalClipetRanking, phase1Matches, type ClipetMatch, type ClipetTeam } from "@/lib/clipet";

type Tournament={id:string;format:string|null;category?:string|null;group_count:number|null;group_names:string[]|null};
type Team=ClipetTeam&{group_idx?:number|null};
type Match=ClipetMatch;
type Classic={team_id:string;team_name:string;played:number;wins:number;draws:number;losses:number;gf:number;ga:number;gd:number;pts:number};
function classic(teams:Team[],matches:Match[]){const m=new Map<string,Classic>();teams.forEach(t=>m.set(t.id,{team_id:t.id,team_name:t.name||'Équipe',played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,pts:0}));for(const x of matches){if(x.status!=='played'||x.home_score==null||x.away_score==null)continue;const h=m.get(x.home_team_id),a=m.get(x.away_team_id);if(!h||!a)continue;h.played++;a.played++;h.gf+=x.home_score;h.ga+=x.away_score;a.gf+=x.away_score;a.ga+=x.home_score;if(x.home_score>x.away_score){h.wins++;a.losses++;h.pts+=3}else if(x.away_score>x.home_score){a.wins++;h.losses++;a.pts+=3}else{h.draws++;a.draws++;h.pts++;a.pts++}}const arr=[...m.values()].map(r=>({...r,gd:r.gf-r.ga}));arr.sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.team_name.localeCompare(b.team_name,'fr'));return arr}
export default function Standings(){const router=useRouter();const tournamentId=String(useParams().id);const [t,setT]=useState<Tournament|null>(null);const [teams,setTeams]=useState<Team[]>([]);const [matches,setMatches]=useState<Match[]>([]);const [status,setStatus]=useState('Chargement…');async function load(){const [{data:tt,error:te},{data:tm,error:tme},{data:mm,error:me}]=await Promise.all([supabase.from('tournaments').select('id,format,category,group_count,group_names').eq('id',tournamentId).single(),supabase.from('teams').select('id,name,group_idx,club_name,squad_number,challenge_disqualified').eq('tournament_id',tournamentId),supabase.from('matches').select('id,match_number,phase,stage,home_team_id,away_team_id,home_score,away_score,status,penalty_home,penalty_away,winner_team_id').eq('tournament_id',tournamentId)]);if(te||tme||me)return setStatus((te||tme||me)?.message||'Erreur');setT(tt as Tournament);setTeams((tm??[]) as Team[]);setMatches((mm??[]) as Match[]);setStatus('')}useEffect(()=>{(async()=>{const {data:a}=await supabase.auth.getUser();if(!a.user)return router.push('/login');load()})()},[tournamentId]);const clipet=t?.format==='michel_clipet';const p1=useMemo(()=>computeClipetStandings(teams,phase1Matches(matches)),[teams,matches]);const final=useMemo(()=>finalClipetRanking(teams,matches),[teams,matches]);const normal=useMemo(()=>classic(teams,matches),[teams,matches]);return <main className="min-h-screen bg-slate-100 p-6"><div className="max-w-5xl mx-auto space-y-4"><div className="bg-white rounded-2xl shadow p-6 flex justify-between"><div><h1 className="text-2xl font-extrabold">Classement {clipet?`Michel Clipet ${t?.category??''}`:''}</h1><p className="text-sm text-gray-500">{clipet?'8 pts victoire · 4 nul · 2 défaite · +1 par but marqué':'Barème classique 3/1/0'}</p></div><button className="bg-gray-200 px-4 py-2 rounded-xl" onClick={()=>router.push(`/dashboard/tournaments/${tournamentId}`)}>← Retour</button></div>{status&&<div className="bg-white p-4 rounded-xl shadow">{status}</div>}
 {clipet&&final&&<div className="bg-white rounded-2xl shadow p-6"><h2 className="font-extrabold text-xl mb-3">🏆 Classement final</h2>{final.map(r=><div key={r.team.id} className="flex justify-between p-2 border-b"><span><b>{r.rank}.</b> {r.team.name}</span><b>{r.challenge_points} pts Challenge</b></div>)}</div>}
 <div className="bg-white rounded-2xl shadow p-6"><h2 className="font-extrabold mb-3">{clipet?'Classement phase 1':'Classement'}</h2><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">#</th><th>Équipe</th><th>Pts</th><th>J</th><th>G</th><th>N</th><th>P</th><th>BP</th><th>BC</th>{!clipet&&<th>Diff</th>}</tr></thead><tbody>{(clipet?p1:normal).map((r:any,i)=><tr key={r.team_id} className="border-b"><td className="p-2 font-bold">{i+1}</td><td>{r.team_name}</td><td className="font-extrabold">{r.pts}</td><td>{r.played}</td><td>{r.wins}</td><td>{r.draws}</td><td>{r.losses}</td><td>{r.gf}</td><td>{r.ga}</td>{!clipet&&<td>{r.gd}</td>}</tr>)}</tbody></table></div>{clipet&&<p className="text-xs text-gray-500 mt-3">Départage réglementaire : points, buts marqués, buts encaissés (moins = mieux), puis tirage au sort.</p>}</div></div></main>}
