"use client";
import { useEffect,useMemo,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import { finalClipetRanking, type ClipetMatch, type ClipetTeam } from "@/lib/clipet";

type T={id:string;title:string;category:string|null;phase1_locked:boolean|null};
type C={id:string;title:string;challenge_date:string|null};
type Ranked={rank:number;team:ClipetTeam;challenge_points:number};
export default function ChallengePage(){
 const {id}=useParams(); const challengeId=String(id); const router=useRouter(); const [challenge,setChallenge]=useState<C|null>(null); const [tournaments,setTournaments]=useState<T[]>([]); const [rankings,setRankings]=useState<Record<string,Ranked[]|null>>({}); const [status,setStatus]=useState('Chargement…');
 async function load(){const {data:a}=await supabase.auth.getUser();if(!a.user)return router.push('/login'); const {data:c,error:ce}=await supabase.from('challenges').select('id,title,challenge_date').eq('id',challengeId).single(); if(ce)return setStatus(ce.message);setChallenge(c as C); const {data:ts,error:te}=await supabase.from('tournaments').select('id,title,category,phase1_locked').eq('challenge_id',challengeId).order('category');if(te)return setStatus(te.message); const list=(ts??[]) as T[];setTournaments(list); const rr:Record<string,Ranked[]|null>={}; for(const t of list){const [{data:teams},{data:matches}]=await Promise.all([supabase.from('teams').select('id,name,club_name,squad_number,challenge_disqualified').eq('tournament_id',t.id),supabase.from('matches').select('id,match_number,phase,stage,home_team_id,away_team_id,home_score,away_score,status,penalty_home,penalty_away,winner_team_id').eq('tournament_id',t.id)]);rr[t.category??t.id]=finalClipetRanking((teams??[]) as ClipetTeam[],(matches??[]) as ClipetMatch[])} setRankings(rr);setStatus('');}
 useEffect(()=>{load()},[challengeId]);
 const combined=useMemo(()=>{const u8=rankings.U8??[];const u9=rankings.U9??[]; const m=new Map<string,{key:string;label:string;u8:number;u9:number;total:number}>(); for(const [cat,arr] of [['U8',u8],['U9',u9]] as const){for(const r of arr||[]){const t=r.team;const key=`${(t.club_name||t.name||'').trim().toLowerCase()}#${t.squad_number??1}`;const label=`${t.club_name||t.name||'Club'} ${t.squad_number&&t.squad_number>1?t.squad_number:''}`.trim();const e=m.get(key)||{key,label,u8:0,u9:0,total:0};const pts=t.challenge_disqualified?0:r.challenge_points;if(cat==='U8')e.u8=pts;else e.u9=pts;e.total=e.u8+e.u9;m.set(key,e)}} return [...m.values()].sort((a,b)=>b.total-a.total||a.label.localeCompare(b.label,'fr'));},[rankings]);
 return <main className="min-h-screen bg-slate-100 p-6"><div className="max-w-6xl mx-auto space-y-4">
  <div className="bg-white rounded-2xl shadow p-6 flex justify-between gap-3 flex-wrap"><div><h1 className="text-2xl font-extrabold">{challenge?.title??'Challenge Michel Clipet'}</h1><p className="text-sm text-gray-500">Deux tournois, 11 rencontres par équipe, classement général combiné.</p></div><button className="bg-gray-200 px-4 py-2 rounded-xl" onClick={()=>router.push('/dashboard/challenges')}>← Challenges</button></div>
  {status&&<div className="bg-white rounded-xl shadow p-4">{status}</div>}
  <div className="grid md:grid-cols-2 gap-4">{tournaments.map(t=><div key={t.id} className="bg-white rounded-2xl shadow p-5"><div className="flex justify-between items-start"><div><div className="text-xs font-bold text-gray-500">{t.category==='U8'?'🔴 U8':'⚫️ U9'}</div><h2 className="font-extrabold text-lg">{t.title}</h2></div><span className={`text-xs px-2 py-1 rounded-full ${t.phase1_locked?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'}`}>{t.phase1_locked?'Phase 1 figée':'Phase 1 ouverte'}</span></div><div className="mt-4 grid grid-cols-2 gap-2"><button className="bg-blue-600 text-white rounded-xl p-3 font-bold" onClick={()=>router.push(`/dashboard/tournaments/${t.id}`)}>Piloter</button><button className="bg-gray-200 rounded-xl p-3" onClick={()=>router.push(`/dashboard/tournaments/${t.id}/standings`)}>Classement</button><button className="bg-gray-200 rounded-xl p-3" onClick={()=>router.push(`/dashboard/tournaments/${t.id}/schedule`)}>Planning</button><button className="bg-gray-200 rounded-xl p-3" onClick={()=>router.push(`/dashboard/tournaments/${t.id}/matches`)}>Matchs</button></div></div>)}</div>
  <div className="bg-white rounded-2xl shadow p-6"><h2 className="text-xl font-extrabold mb-3">🏆 Classement général du Challenge</h2>{combined.length===0?<p className="text-gray-500">Le classement général apparaîtra lorsque les classements finaux U8 et U9 seront disponibles.</p>:<div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">#</th><th>Club / équipe</th><th>U8</th><th>U9</th><th>Total</th></tr></thead><tbody>{combined.map((r,i)=><tr key={r.key} className="border-b"><td className="p-2 font-bold">{i+1}</td><td className="font-semibold">{r.label}</td><td>{r.u8}</td><td>{r.u9}</td><td className="font-extrabold">{r.total}</td></tr>)}</tbody></table></div>}</div>
 </div></main>
}
