"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import { computeChallengeStandings, rankTournamentTeams, TeamStats, TieBreaker } from "@/lib/challenge";
import { rankMichelFinal } from "@/lib/tournamentPhases";

type Challenge = { id:string; title:string; event_date:string|null; venue:string|null; field_names:string[]; match_duration_min:number; display_theme:string; display_logo_url:string|null; display_banners:string[]; scoring_mode:"placement_points"|"tournament_points"|"goals_scored"; default_points_by_rank:number[]; tie_breakers:TieBreaker[] };
type Link = { tournament_id:string; position:number; points_by_rank:number[]|null; tournament:{id:string;title:string;display_label:string|null;format:string|null;scoring_rules:{win?:number;draw?:number;loss?:number;goal_bonus?:number}|null}|null };
type Team = { id:string;tournament_id:string;name:string;challenge_name:string|null };
type Match = { id:string;tournament_id:string;match_number:number|null;stage:string|null;start_time:string;field_idx:number;status:string;home_team_id:string|null;away_team_id:string|null;home_score:number|null;away_score:number|null;home_source_label:string|null;away_source_label:string|null;referee_label:string|null };
type EventRow = {id:string;title:string;start_time:string;duration_minutes:number;event_type:string};
type View = "schedule"|"selectors"|"tournament"|"challenge";
type Palette = {bg:string;panel:string;soft:string;accent:string;strong:string;text:string;muted:string;card:string};

const PALETTES:Record<string,Palette> = {
  blue:{bg:"#050322",panel:"#042b42",soft:"#0b3b55",accent:"#86a9c2",strong:"#58bce8",text:"#fff",muted:"#b9cbd8",card:"#f7fafc"},
  red:{bg:"#22040a",panel:"#5b1520",soft:"#7b2330",accent:"#c88991",strong:"#ff5a67",text:"#fff",muted:"#ead0d4",card:"#fff8f8"},
  orange:{bg:"#241006",panel:"#71320f",soft:"#904718",accent:"#d69258",strong:"#ff9a3c",text:"#fff",muted:"#f2d9c4",card:"#fffaf5"},
  green:{bg:"#031d15",panel:"#15513c",soft:"#1f6a51",accent:"#75b39a",strong:"#48d59c",text:"#fff",muted:"#cde5dc",card:"#f5fcf9"},
  yellow:{bg:"#231d04",panel:"#6b570a",soft:"#8d7410",accent:"#e0bf4f",strong:"#ffd83d",text:"#fff",muted:"#f4e9b1",card:"#fffdf3"},
  purple:{bg:"#16051f",panel:"#4c2361",soft:"#68337f",accent:"#a981bd",strong:"#d38cff",text:"#fff",muted:"#e4d2ec",card:"#fcf8ff"},
  sky:{bg:"#041e2a",panel:"#165b74",soft:"#237896",accent:"#82bfd6",strong:"#55d4ff",text:"#fff",muted:"#d1eaf3",card:"#f5fcff"}
};
const hhmm=(s:string)=>s?.slice(0,5)||"--:--";
const mins=(s:string)=>{const [h,m]=hhmm(s).split(":").map(Number);return h*60+m};
const nameOf=(id:string|null,label:string|null,teams:Team[])=>teams.find(t=>t.id===id)?.name||label||"À déterminer";

export default function ChallengePublicScreen(){
  const id=String(useParams().id); const [challenge,setChallenge]=useState<Challenge|null>(null); const [links,setLinks]=useState<Link[]>([]); const [teams,setTeams]=useState<Team[]>([]); const [matches,setMatches]=useState<Match[]>([]); const [events,setEvents]=useState<EventRow[]>([]); const [view,setView]=useState<View>("schedule"); const [selectedTournament,setSelectedTournament]=useState<string|null>(null); const [status,setStatus]=useState("Chargement de l’affichage…");
  async function load(){
    const {data:c,error}=await supabase.from("challenges").select("id,title,event_date,venue,field_names,match_duration_min,display_theme,display_logo_url,display_banners,scoring_mode,default_points_by_rank,tie_breakers").eq("id",id).single(); if(error)return setStatus(`Affichage indisponible : ${error.message}`);
    const {data:l}=await supabase.from("challenge_tournaments").select("tournament_id,position,points_by_rank,tournament:tournament_id(id,title,display_label,format,scoring_rules)").eq("challenge_id",id).order("position"); const ls=(l??[]) as unknown as Link[]; const ids=ls.map(x=>x.tournament_id);
    const [{data:t},{data:m},{data:e}]=await Promise.all([supabase.from("teams").select("id,tournament_id,name,challenge_name").in("tournament_id",ids),supabase.from("matches").select("id,tournament_id,match_number,stage,start_time,field_idx,status,home_team_id,away_team_id,home_score,away_score,home_source_label,away_source_label,referee_label").in("tournament_id",ids).order("start_time").order("field_idx"),supabase.from("challenge_events").select("id,title,start_time,duration_minutes,event_type").eq("challenge_id",id).order("start_time")]);
    setChallenge(c as Challenge);setLinks(ls);setSelectedTournament(v=>v??ids[0]??null);setTeams((t??[]) as Team[]);setMatches((m??[]) as Match[]);setEvents((e??[]) as EventRow[]);setStatus("");
  }
  useEffect(()=>{load();const timer=window.setInterval(load,10000);return()=>window.clearInterval(timer);/* eslint-disable-next-line react-hooks/exhaustive-deps */},[id]);
  const ranked=useMemo(()=>{const out:TeamStats[]=[];for(const l of links){const rules=l.tournament?.scoring_rules??{};if(l.tournament?.format==="hybrid"){out.push(...rankMichelFinal(teams,matches.filter(m=>m.tournament_id===l.tournament_id),l.tournament_id,rules));continue}const win=Number(rules.win??3),draw=Number(rules.draw??1),loss=Number(rules.loss??0),bonus=Number(rules.goal_bonus??0);const rows=teams.filter(t=>t.tournament_id===l.tournament_id).map(team=>{let played=0,points=0,goalsFor=0,goalsAgainst=0;for(const m of matches.filter(m=>m.tournament_id===team.tournament_id&&m.status==="played")){if(m.home_score==null||m.away_score==null)continue;const home=m.home_team_id===team.id,away=m.away_team_id===team.id;if(!home&&!away)continue;played++;const gf=home?m.home_score:m.away_score,ga=home?m.away_score:m.home_score;goalsFor+=gf;goalsAgainst+=ga;points+=(gf>ga?win:gf===ga?draw:loss)+gf*bonus}return{id:team.id,name:team.name,challengeName:team.challenge_name?.trim()||team.name,tournamentId:team.tournament_id,played,points,goalsFor,goalsAgainst}});out.push(...rankTournamentTeams(rows))}return out},[links,teams,matches]);
  const challengeRanks=useMemo(()=>challenge?computeChallengeStandings(ranked,challenge.scoring_mode,challenge.default_points_by_rank,Object.fromEntries(links.map(l=>[l.tournament_id,l.points_by_rank??challenge.default_points_by_rank])),challenge.tie_breakers):[],[challenge,ranked,links]);
  if(!challenge)return <main className="min-h-screen bg-[#050322] text-white grid place-items-center p-8 text-xl">{status}</main>;
  const p=PALETTES[challenge.display_theme]??PALETTES.blue, selected=links.find(l=>l.tournament_id===selectedTournament), year=challenge.event_date?new Date(`${challenge.event_date}T12:00:00`).getFullYear():new Date().getFullYear();
  return <main className="min-h-screen overflow-x-hidden" style={{background:`radial-gradient(circle at 50% -20%,${p.soft} 0%,${p.bg} 42%)`,color:p.text}}><div className="mx-auto max-w-[1920px] px-3 py-4 sm:px-6 lg:px-10 lg:py-8">
    <header className="mb-5 flex items-center gap-4 lg:gap-7">{challenge.display_logo_url&&<div className="hidden h-24 w-24 shrink-0 place-items-center rounded-3xl border border-white/15 bg-white/5 p-2 shadow-2xl sm:grid lg:h-32 lg:w-32"><img src={challenge.display_logo_url} alt="Logo du challenge" className="h-full w-full object-contain"/></div>}<div className="min-w-0 flex-1"><div className="mb-1 flex items-center gap-3 text-[10px] font-extrabold uppercase tracking-[.24em] sm:text-sm" style={{color:p.muted}}><span>Doppietta Gestion Tournament</span><span className="hidden h-px flex-1 bg-white/15 sm:block"/></div><h1 className="max-w-full break-words text-[clamp(2rem,6vw,7.6rem)] font-black uppercase leading-[.86] tracking-[-.045em]">{challenge.title} <span style={{color:p.strong}}>· {year}</span></h1>{(challenge.venue||challenge.event_date)&&<p className="mt-3 text-xs font-semibold uppercase tracking-[.18em] sm:text-base" style={{color:p.muted}}>{challenge.event_date&&new Intl.DateTimeFormat("fr-FR",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${challenge.event_date}T12:00:00`))}{challenge.event_date&&challenge.venue?" · ":""}{challenge.venue}</p>}</div><div className="hidden shrink-0 items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-bold uppercase tracking-widest lg:flex"><span className="h-2 w-2 animate-pulse rounded-full" style={{background:p.strong}}/>Actualisation auto</div></header>
    <Banners values={challenge.display_banners} panel={p.panel}/>
    <nav className="sticky top-3 z-40 mb-5 flex justify-center gap-2 sm:justify-end"><Nav active={view==="schedule"} label="Déroulé des événements" icon="↩" onClick={()=>setView("schedule")} p={p}/><Nav active={view!=="schedule"} label="Classements en cours" icon="🏆" onClick={()=>setView("selectors")} p={p}/></nav>
    <div className="transition-all duration-500">{view==="schedule"&&<Schedule matches={matches} events={events} teams={teams} links={links} fields={challenge.field_names} duration={challenge.match_duration_min} p={p}/>} {view==="selectors"&&<Selectors links={links} p={p} tournament={x=>{setSelectedTournament(x);setView("tournament")}} challenge={()=>setView("challenge")}/>} {view==="tournament"&&<Ranking title={selected?.tournament?.display_label||selected?.tournament?.title||"Tournoi"} subtitle={selected?.tournament?.title||"Classement du tournoi"} rows={ranked.filter(r=>r.tournamentId===selectedTournament).map(r=>({name:r.name,played:r.played,points:r.points,gf:r.goalsFor,gd:r.goalDifference}))} p={p} back={()=>setView("selectors")}/>} {view==="challenge"&&<Ranking title="Challenge 🏆" subtitle="Classement général en direct" rows={challengeRanks.map(r=>({name:r.name,played:r.tournamentsPlayed,points:r.score,gf:r.goalsFor,gd:r.goalDifference}))} p={p} back={()=>setView("selectors")}/>}</div>
  </div></main>
}

function Banners({values,panel}:{values:string[];panel:string}){const slots=[values?.[0],values?.[1],values?.[2]];if(!slots.some(Boolean))return null;return <section className="mb-4 grid grid-cols-2 items-center gap-2 sm:gap-4 lg:grid-cols-[1fr_1.5fr_1fr] lg:gap-8">{slots.map((v,i)=><div key={i} className={`${i===1?"order-first col-span-2 h-[clamp(90px,14vw,230px)] lg:order-none lg:col-span-1":"h-[clamp(72px,9vw,150px)]"} overflow-hidden rounded-2xl border border-white/10 shadow-2xl`} style={{background:panel}}>{v?<img src={v} alt={`Bannière ${i+1}`} className="h-full w-full object-cover"/>:<div className="h-full bg-white/5"/>}</div>)}</section>}
function Nav({active,label,icon,onClick,p}:{active:boolean;label:string;icon:string;onClick:()=>void;p:Palette}){return <button onClick={onClick} className="min-h-11 rounded-full border px-3 py-2 text-[11px] font-black uppercase tracking-wide shadow-xl transition duration-300 hover:-translate-y-0.5 focus:ring-2 focus:ring-white sm:px-5 sm:text-sm" style={{background:active?"#fff":p.panel,color:active?p.bg:p.text,borderColor:active?"#fff":`${p.accent}55`}}>{icon} {label}</button>}

function Schedule({matches,events,teams,links,fields,duration,p}:{matches:Match[];events:EventRow[];teams:Team[];links:Link[];fields:string[];duration:number;p:Palette}){const now=new Date(),nowMin=now.getHours()*60+now.getMinutes(),done=matches.filter(m=>m.status==="played").sort((a,b)=>mins(b.start_time)-mins(a.start_time)),pending=matches.filter(m=>m.status!=="played"),live=pending.filter(m=>mins(m.start_time)<=nowMin&&nowMin<mins(m.start_time)+duration),upcoming=pending.filter(m=>!live.includes(m));const timeline=[...upcoming.map(match=>({kind:"match" as const,time:mins(match.start_time),match})),...events.filter(e=>mins(e.start_time)+e.duration_minutes>nowMin).map(event=>({kind:"event" as const,time:mins(event.start_time),event}))].sort((a,b)=>a.time-b.time);return <div className="space-y-5">{live.length>0&&<MatchSection title="Événements en direct" eyebrow="Maintenant" rows={live} {...{teams,links,fields,p}} live/>}<section className="overflow-hidden rounded-[28px] border border-white/10 shadow-2xl" style={{background:p.panel}}><SectionTitle title="Événements à venir" eyebrow="Programme" p={p}/><div className="space-y-3 p-3 sm:p-5">{timeline.length?group(timeline).map(([time,items])=><div key={time} className="grid gap-3 lg:grid-cols-[90px_1fr]"><div className="flex items-center gap-2 px-1 text-lg font-black lg:flex-col lg:justify-center lg:text-2xl"><span>⏱</span><span>{time}</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(item=>item.kind==="match"?<MatchCard key={item.match.id} m={item.match} {...{teams,links,fields,p}}/>:<EventCard key={item.event.id} e={item.event} p={p}/>)}</div></div>):<Empty label="Aucun événement à venir"/>}</div></section>{done.length>0&&<MatchSection title="Matchs réalisés" eyebrow="Résultats" rows={done} {...{teams,links,fields,p}}/>}</div>}
function group(items:Array<{kind:"match";time:number;match:Match}|{kind:"event";time:number;event:EventRow}>){const map=new Map<string,typeof items>();for(const item of items){const label=`${String(Math.floor(item.time/60)).padStart(2,"0")}:${String(item.time%60).padStart(2,"0")}`;map.set(label,[...(map.get(label)??[]),item])}return Array.from(map.entries())}
function MatchSection({title,eyebrow,rows,teams,links,fields,p,live=false}:{title:string;eyebrow:string;rows:Match[];teams:Team[];links:Link[];fields:string[];p:Palette;live?:boolean}){return <section className="overflow-hidden rounded-[28px] border border-white/10 shadow-2xl" style={{background:p.panel}}><SectionTitle {...{title,eyebrow,p,live}}/><div className="grid gap-3 p-3 sm:grid-cols-2 sm:p-5 xl:grid-cols-4">{rows.map(m=><MatchCard key={m.id} {...{m,teams,links,fields,p}}/>)}</div></section>}
function SectionTitle({title,eyebrow,p,live=false}:{title:string;eyebrow:string;p:Palette;live?:boolean}){return <header className="flex items-end justify-between gap-3 border-b border-white/10 px-4 py-4 sm:px-6"><div><p className="text-[10px] font-black uppercase tracking-[.28em]" style={{color:p.accent}}>{eyebrow}</p><h2 className="text-xl font-black uppercase tracking-tight sm:text-3xl">{title}</h2></div>{live&&<span className="flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-xs font-black uppercase"><span className="h-2.5 w-2.5 animate-pulse rounded-full" style={{background:p.strong}}/>Live</span>}</header>}
function MatchCard({m,teams,links,fields,p}:{m:Match;teams:Team[];links:Link[];fields:string[];p:Palette}){const played=m.status==="played",mark=links.find(l=>l.tournament_id===m.tournament_id)?.tournament?.display_label||"",home=nameOf(m.home_team_id,m.home_source_label,teams),away=nameOf(m.away_team_id,m.away_source_label,teams);return <article className="group relative min-h-[190px] overflow-hidden rounded-2xl border border-slate-200/80 p-4 text-slate-950 shadow-lg transition duration-300 hover:-translate-y-1 hover:shadow-2xl" style={{background:played?"#e5e7eb":p.card}}><div className="absolute inset-x-0 top-0 h-1" style={{background:p.strong}}/><div className="flex items-start justify-between gap-3 text-xs font-extrabold uppercase tracking-wide text-slate-500"><span>⏱ {hhmm(m.start_time)}</span><span className="max-w-[65%] break-words text-right">🏟 {fields?.[m.field_idx-1]||`Terrain ${m.field_idx}`}</span></div><div className="my-5 grid min-h-[82px] place-items-center text-center text-[clamp(.78rem,1.15vw,1.16rem)] font-black uppercase leading-[1.05]"><div className="w-full break-words">{home}</div><div className="my-1 text-[10px] text-slate-400">CONTRE</div><div className="w-full break-words">{away}</div></div><div className="flex items-end justify-between gap-3"><span className="rounded-full px-3 py-1 text-sm font-black" style={{background:`${p.accent}44`,color:p.panel}}>🏆 {mark}</span><span className="max-w-[66%] break-words text-right text-sm font-black text-slate-600">{played?<strong className="text-xl text-slate-950">✓ {m.home_score??0}–{m.away_score??0}</strong>:`👤 ${m.referee_label||"À désigner"}`}</span></div></article>}
function EventCard({e,p}:{e:EventRow;p:Palette}){return <article className="relative col-span-full min-h-28 overflow-hidden rounded-2xl bg-white p-5 text-slate-950 shadow-lg"><div className="absolute inset-y-0 left-0 w-2" style={{background:p.strong}}/><div className="flex h-full flex-col justify-center gap-1 pl-2 sm:flex-row sm:items-center sm:justify-between"><div className="font-black uppercase text-slate-500">⏱ {hhmm(e.start_time)} · {e.duration_minutes} min</div><h3 className="break-words text-xl font-black uppercase sm:text-3xl">{e.title}</h3></div></article>}
function Empty({label}:{label:string}){return <div className="col-span-full rounded-2xl border border-dashed border-white/25 p-8 text-center font-bold text-white/60">{label}</div>}

function Selectors({links,p,tournament,challenge}:{links:Link[];p:Palette;tournament:(id:string)=>void;challenge:()=>void}){return <section className="grid min-h-[55vh] place-items-center py-8"><div className="w-full max-w-6xl"><p className="mb-6 text-center text-xs font-black uppercase tracking-[.35em]" style={{color:p.accent}}>Les classements</p><div className="grid gap-5 md:grid-cols-2">{links.map(l=><button key={l.tournament_id} onClick={()=>tournament(l.tournament_id)} className="group relative min-h-48 overflow-hidden rounded-[32px] border border-white/20 p-8 text-left shadow-2xl transition duration-300 hover:-translate-y-1" style={{background:`linear-gradient(135deg,${p.accent},${p.soft})`}}><span className="text-xs font-black uppercase tracking-[.28em]">Classement</span><span className="mt-5 block break-words text-[clamp(3rem,8vw,7rem)] font-black uppercase leading-none">{l.tournament?.display_label||l.tournament?.title}</span><span className="absolute bottom-6 right-7 text-3xl transition group-hover:translate-x-2">→</span></button>)}<button onClick={challenge} className="group relative min-h-52 overflow-hidden rounded-[32px] border border-white/20 p-8 text-left shadow-2xl transition duration-300 hover:-translate-y-1 md:col-span-2" style={{background:p.panel}}><span className="text-xs font-black uppercase tracking-[.28em]" style={{color:p.accent}}>Classement général</span><span className="mt-5 block break-words text-[clamp(2.7rem,8vw,7.5rem)] font-black uppercase leading-none">Challenge 🏆</span><span className="absolute bottom-6 right-7 text-3xl transition group-hover:translate-x-2">→</span></button></div></div></section>}
function Ranking({title,subtitle,rows,p,back}:{title:string;subtitle:string;rows:Array<{name:string;played:number;points:number;gf:number;gd:number}>;p:Palette;back:()=>void}){return <section className="mx-auto max-w-7xl py-5"><button className="mb-5 rounded-full border border-white/15 bg-white/10 px-5 py-2 text-sm font-black uppercase transition hover:bg-white hover:text-slate-950" onClick={back}>← Tous les classements</button><header className="mb-7 text-center"><p className="text-xs font-black uppercase tracking-[.3em]" style={{color:p.accent}}>{subtitle}</p><h2 className="break-words text-[clamp(3rem,8vw,7.5rem)] font-black uppercase leading-none">{title}</h2></header><div className="overflow-hidden rounded-[28px] border border-white/10 shadow-2xl" style={{background:p.panel}}><div className="hidden grid-cols-[70px_minmax(260px,1fr)_repeat(4,minmax(75px,110px))] gap-2 px-4 py-3 text-center text-[10px] font-black uppercase tracking-widest text-white/70 md:grid"><span/><span className="text-left">Équipe</span><span>Matchs</span><span>Points</span><span>Buts</span><span>Diff.</span></div><div className="space-y-2 p-2 sm:p-4">{rows.map((r,i)=><div key={`${r.name}-${i}`} className="grid grid-cols-[42px_minmax(0,1fr)_repeat(4,42px)] items-stretch gap-1 text-slate-950 sm:grid-cols-[56px_minmax(0,1fr)_repeat(4,60px)] sm:gap-2 md:grid-cols-[70px_minmax(260px,1fr)_repeat(4,minmax(75px,110px))]"><strong className="grid min-h-16 place-items-center rounded-l-xl bg-white text-xl sm:text-2xl">{i+1}</strong><strong className="flex min-w-0 items-center break-words px-2 py-3 text-[clamp(.68rem,1.5vw,1.25rem)] font-black uppercase leading-tight sm:px-4" style={{background:p.accent}}>{r.name}</strong>{[r.played,r.points,r.gf,`${r.gd>0?"+":""}${r.gd}`].map((v,j)=><span key={j} className="grid place-items-center bg-white text-xs font-black sm:text-base">{v}</span>)}</div>)}</div></div></section>}
