"use client";

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { supabase } from "@/lib/supabaseClient";
import { computeChallengeStandings, rankTournamentTeams, TeamStats, TieBreaker } from "@/lib/challenge";

type Challenge = { id:string; title:string; field_names:string[]; match_duration_min:number; rotation_duration_min:number; display_theme:string; display_logo_url:string|null; display_banners:string[]; scoring_mode:"placement_points"|"tournament_points"|"goals_scored"; default_points_by_rank:number[]; tie_breakers:TieBreaker[] };
type Link = { tournament_id:string; position:number; points_by_rank:number[]|null; tournament:{id:string;title:string;display_label:string|null;scoring_rules:{win?:number;draw?:number;loss?:number;goal_bonus?:number}|null}|null };
type Team = { id:string;tournament_id:string;name:string;challenge_name:string|null };
type Match = { id:string;tournament_id:string;start_time:string;field_idx:number;status:string;home_team_id:string|null;away_team_id:string|null;home_score:number|null;away_score:number|null;home_source_label:string|null;away_source_label:string|null;referee:{name:string}|null };
type EventRow = {id:string;title:string;start_time:string;duration_minutes:number;event_type:string};
type View = "schedule"|"selectors"|"tournament"|"challenge";

const PALETTES:Record<string,{bg:string;panel:string;accent:string;text:string;muted:string}> = {
  blue:{bg:"#05022d",panel:"#062f48",accent:"#83a8c4",text:"#ffffff",muted:"#dce7ee"}, red:{bg:"#26040b",panel:"#651b24",accent:"#b56c72",text:"#fff",muted:"#f4e2e4"},
  orange:{bg:"#291006",panel:"#77320f",accent:"#ce7a35",text:"#fff",muted:"#fae7d7"}, green:{bg:"#041e16",panel:"#185640",accent:"#69a78f",text:"#fff",muted:"#dcece6"},
  yellow:{bg:"#2c2303",panel:"#765d09",accent:"#e0b929",text:"#fff",muted:"#fff5c7"}, purple:{bg:"#17051f",panel:"#522668",accent:"#9d70b4",text:"#fff",muted:"#eee0f5"}, sky:{bg:"#06212d",panel:"#185f7a",accent:"#75b6cf",text:"#fff",muted:"#dff1f8"}
};
const hhmm=(s:string)=>s?.slice(0,5)||"--:--";
const mins=(s:string)=>{const [h,m]=hhmm(s).split(":").map(Number);return h*60+m};
const teamName=(id:string|null,label:string|null,teams:Team[])=>teams.find(t=>t.id===id)?.name||label||"À déterminer";

export default function ChallengePublicScreen(){
  const id=String(useParams().id); const [challenge,setChallenge]=useState<Challenge|null>(null); const [links,setLinks]=useState<Link[]>([]); const [teams,setTeams]=useState<Team[]>([]); const [matches,setMatches]=useState<Match[]>([]); const [events,setEvents]=useState<EventRow[]>([]); const [view,setView]=useState<View>("schedule"); const [selectedTournament,setSelectedTournament]=useState<string|null>(null); const [status,setStatus]=useState("Chargement...");
  async function load(){
    const {data:c,error}=await supabase.from("challenges").select("id,title,field_names,match_duration_min,rotation_duration_min,display_theme,display_logo_url,display_banners,scoring_mode,default_points_by_rank,tie_breakers").eq("id",id).single(); if(error)return setStatus("Affichage indisponible: "+error.message);
    const {data:l}=await supabase.from("challenge_tournaments").select("tournament_id,position,points_by_rank,tournament:tournament_id(id,title,display_label,scoring_rules)").eq("challenge_id",id).order("position"); const ls=(l??[]) as unknown as Link[]; const ids=ls.map(x=>x.tournament_id);
    const [{data:t},{data:m},{data:e}]=await Promise.all([supabase.from("teams").select("id,tournament_id,name,challenge_name").in("tournament_id",ids),supabase.from("matches").select("id,tournament_id,start_time,field_idx,status,home_team_id,away_team_id,home_score,away_score,home_source_label,away_source_label,referee:referee_team_id(name)").in("tournament_id",ids).order("start_time").order("field_idx"),supabase.from("challenge_events").select("id,title,start_time,duration_minutes,event_type").eq("challenge_id",id).order("start_time")]);
    setChallenge(c as Challenge);setLinks(ls);setSelectedTournament(v=>v??ids[0]??null);setTeams((t??[]) as Team[]);setMatches((m??[]) as unknown as Match[]);setEvents((e??[]) as EventRow[]);setStatus("");
  }
  useEffect(()=>{load();const timer=setInterval(load,10000);return()=>clearInterval(timer);/* eslint-disable-next-line react-hooks/exhaustive-deps */},[id]);
  const ranked=useMemo(()=>{const out:TeamStats[]=[];for(const l of links){const rules=l.tournament?.scoring_rules??{};const win=Number(rules.win??3),draw=Number(rules.draw??1),loss=Number(rules.loss??0),bonus=Number(rules.goal_bonus??0);const rows=teams.filter(t=>t.tournament_id===l.tournament_id).map(team=>{let played=0,points=0,goalsFor=0,goalsAgainst=0;for(const m of matches.filter(m=>m.tournament_id===team.tournament_id&&m.status==="played")){if(m.home_score==null||m.away_score==null)continue;const home=m.home_team_id===team.id,away=m.away_team_id===team.id;if(!home&&!away)continue;played++;const gf=home?m.home_score:m.away_score,ga=home?m.away_score:m.home_score;goalsFor+=gf;goalsAgainst+=ga;points+=(gf>ga?win:gf===ga?draw:loss)+gf*bonus}return{id:team.id,name:team.name,challengeName:team.challenge_name?.trim()||team.name,tournamentId:team.tournament_id,played,points,goalsFor,goalsAgainst}});out.push(...rankTournamentTeams(rows))}return out},[links,teams,matches]);
  const challengeRanks=useMemo(()=>challenge?computeChallengeStandings(ranked,challenge.scoring_mode,challenge.default_points_by_rank,Object.fromEntries(links.map(l=>[l.tournament_id,l.points_by_rank??challenge.default_points_by_rank])),challenge.tie_breakers):[],[challenge,ranked,links]);
  if(!challenge)return <main className="min-h-screen bg-slate-950 text-white grid place-items-center text-xl">{status}</main>;
  const p=PALETTES[challenge.display_theme]??PALETTES.blue; const selected=links.find(l=>l.tournament_id===selectedTournament);
  return <main className="min-h-screen p-[clamp(12px,2vw,32px)]" style={{background:p.bg,color:p.text}}><div className="max-w-[1800px] mx-auto">
    <header className="flex items-center justify-between gap-4 mb-5"><div className="flex items-center gap-4 min-w-0">{challenge.display_logo_url&&<img src={challenge.display_logo_url} alt="Logo" className="w-[clamp(52px,7vw,110px)] h-[clamp(52px,7vw,110px)] object-contain shrink-0"/>}<div className="min-w-0"><p className="uppercase font-bold tracking-widest text-[clamp(8px,1vw,15px)]" style={{color:p.muted}}>Doppietta Gestion Tournament</p><h1 className="uppercase font-black leading-none break-words text-[clamp(28px,5.2vw,92px)]">{challenge.title}</h1></div></div><div className="flex gap-2 shrink-0"><button onClick={()=>setView("schedule")} className="px-3 py-2 rounded-lg font-bold" style={{background:p.panel}}>↩ Déroulé</button><button onClick={()=>setView("selectors")} className="px-3 py-2 rounded-lg font-bold bg-white text-slate-900">Classements</button></div></header>
    <Banners values={challenge.display_banners} panel={p.panel}/>
    {view==="schedule"&&<Schedule matches={matches} events={events} teams={teams} links={links} fields={challenge.field_names} duration={challenge.match_duration_min} panel={p.panel} accent={p.accent}/>} 
    {view==="selectors"&&<section className="min-h-[55vh] grid place-items-center"><div className="grid md:grid-cols-2 gap-6 w-full max-w-5xl">{links.map(l=><button key={l.tournament_id} onClick={()=>{setSelectedTournament(l.tournament_id);setView("tournament")}} className="border-2 rounded-xl p-10 uppercase text-[clamp(28px,5vw,70px)] font-black" style={{background:p.accent,borderColor:p.muted}}>{l.tournament?.display_label||l.tournament?.title}</button>)}<button onClick={()=>setView("challenge")} className="md:col-span-2 border-2 rounded-xl p-10 uppercase text-[clamp(28px,5vw,70px)] font-black" style={{background:p.panel,borderColor:p.muted}}>Challenge 🏆</button></div></section>}
    {view==="tournament"&&<Ranking title={selected?.tournament?.display_label||selected?.tournament?.title||"Tournoi"} rows={ranked.filter(r=>r.tournamentId===selectedTournament).map(r=>({name:r.name,played:r.played,points:r.points,gf:r.goalsFor,gd:r.goalDifference}))} accent={p.accent} panel={p.panel}/>} 
    {view==="challenge"&&<Ranking title="Challenge 🏆" rows={challengeRanks.map(r=>({name:r.name,played:r.tournamentsPlayed,points:r.score,gf:r.goalsFor,gd:r.goalDifference}))} accent={p.accent} panel={p.panel}/>} 
  </div></main>
}

function Banners({values,panel}:{values:string[];panel:string}){if(!values?.length)return null;const arr=[values[0],values[1],values[2]].filter(Boolean);return <div className="grid grid-cols-[1fr_1.5fr_1fr] gap-[clamp(8px,2vw,40px)] items-center mb-5">{[0,1,2].map(i=><div key={i} className={`${i===1?"h-[clamp(70px,10vw,160px)]":"h-[clamp(55px,8vw,125px)]"} rounded-lg overflow-hidden`} style={{background:panel}}>{arr[i]&&<img src={arr[i]} alt="Bannière" className="w-full h-full object-contain"/>}</div>)}</div>}
function Schedule({matches,events,teams,links,fields,duration,panel,accent}:{matches:Match[];events:EventRow[];teams:Team[];links:Link[];fields:string[];duration:number;panel:string;accent:string}){const now=new Date();const nowMin=now.getHours()*60+now.getMinutes();const done=matches.filter(m=>m.status==="played").reverse();const pending=matches.filter(m=>m.status!=="played");const live=pending.filter(m=>mins(m.start_time)<=nowMin&&nowMin<mins(m.start_time)+duration);const upcoming=pending.filter(m=>!live.includes(m));return <div className="space-y-5"><MatchSection title="Événements en direct" rows={live} {...{teams,links,fields,panel,accent}}/>{upcoming.length>0&&<MatchSection title="Événements à venir" rows={upcoming} {...{teams,links,fields,panel,accent}}/>}{events.map(e=><div key={e.id} className="bg-white text-slate-900 rounded-lg px-6 py-5 flex justify-between items-center text-[clamp(16px,2vw,34px)]"><span>⏱ {hhmm(e.start_time)} · {e.duration_minutes?`${e.duration_minutes} min`:""}</span><strong>{e.title}</strong></div>)}{done.length>0&&<MatchSection title="Matchs réalisés" rows={done} {...{teams,links,fields,panel,accent}}/>}</div>}
function MatchSection({title,rows,teams,links,fields,panel,accent}:{title:string;rows:Match[];teams:Team[];links:Link[];fields:string[];panel:string;accent:string}){if(!rows.length&&title.includes("direct"))return null;return <section className="rounded-xl p-3" style={{background:panel}}><h2 className="uppercase font-black text-[clamp(14px,1.5vw,25px)] mb-3">{title}</h2><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3">{rows.map(m=>{const played=m.status==="played";const mark=links.find(l=>l.tournament_id===m.tournament_id)?.tournament?.display_label||"";return <article key={m.id} className={`${played?"bg-slate-200":"bg-white"} text-slate-900 rounded-lg p-4 min-h-40 flex flex-col justify-between`}><div className="flex justify-between gap-2 text-sm text-slate-500"><span>⏱ {hhmm(m.start_time)}</span><span className="font-bold break-words text-right">🏟 {fields[m.field_idx-1]||`Terrain ${m.field_idx}`}</span></div><div className="text-center font-black uppercase leading-tight my-3 text-[clamp(13px,1.15vw,21px)] break-words"><div>{teamName(m.home_team_id,m.home_source_label,teams)}</div><div className="text-xs my-1">×</div><div>{teamName(m.away_team_id,m.away_source_label,teams)}</div></div><div className="flex justify-between items-end"><span className="font-bold" style={{color:accent}}>🏆 {mark}</span><span className="font-black text-xl">{played?`✓ ${m.home_score??0}-${m.away_score??0}`:`👤 ${m.referee?.name||"À désigner"}`}</span></div></article>})}</div></section>}
function Ranking({title,rows,accent,panel}:{title:string;rows:Array<{name:string;played:number;points:number;gf:number;gd:number}>;accent:string;panel:string}){return <section className="max-w-7xl mx-auto"><button className="mb-4 px-4 py-2 rounded-lg bg-white text-slate-900 font-bold" onClick={()=>history.back()}>← Retour</button><h2 className="text-center uppercase text-[clamp(35px,6vw,90px)] font-black mb-6">{title}</h2><div className="grid lg:grid-cols-2 gap-3">{rows.map((r,i)=><div key={r.name} className="grid grid-cols-[55px_1fr_repeat(4,minmax(46px,85px))] gap-2 items-stretch text-slate-900"><strong className="bg-white rounded-l-xl grid place-items-center text-2xl">{i+1}</strong><strong className="px-4 py-4 uppercase break-words leading-tight text-[clamp(13px,1.3vw,21px)]" style={{background:accent}}>{r.name}</strong>{[r.played,r.points,r.gf,(r.gd>0?"+":"")+r.gd].map((v,j)=><span key={j} className="bg-white grid place-items-center font-black">{v}</span>)}</div>)}</div><div className="mt-4 grid grid-cols-4 gap-2 max-w-md ml-auto text-center text-xs uppercase font-bold" style={{color:panel}}><span>Matchs</span><span>Points</span><span>Buts</span><span>Diff.</span></div></section>}
